In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
import jupyterthemes as jt
jt.jtplot.style(theme = 'grade3', context = 'paper', ticks=True, grid = False)

In [17]:
zee = pd.read_csv('Zee.csv', header = 0)
zee.head(5)

Run      Event      pt1    eta1    phi1  Q1 type1  sigmaEtaEta1  \
0  163286  109060857  37.5667  2.2892  2.0526  -1    EE        0.0251   
1  163286  109275715  36.2901 -0.8373 -1.5859   1    EB        0.0078   
2  163286  109075352  25.9705 -0.6974  1.6360  -1    EB        0.0097   
3  163286  109169766  41.0075  1.4619 -0.5325   1    EB        0.0088   
4  163286  108947653  39.8985 -0.5927 -2.3947   1    EB        0.0153   

   HoverE1  isoTrack1  ...      pt2    eta2    phi2  Q2  type2  sigmaEtaEta2  \
0   0.0090     0.0000  ...  45.4315  1.4706 -1.1630   1     EB        0.0008   
1   0.0438     0.0000  ...  60.5754 -0.4896  1.0496  -1     EB        0.0112   
2   0.0407     6.2870  ...  45.2954 -2.0401  3.1187   1     EE        0.0260   
3   0.0000     0.0000  ...  45.9013  1.1561  2.4786  -1     EB        0.0086   
4   0.0000     2.5435  ...  34.8931 -2.2444  0.6106  -1     EE        0.0290   

  HoverE2  isoTrack2  isoEcal2  isoHcal2  
0   0.000     0.0000    1.0190    0.0000  
1   0.000     0.7185    1.8461    0.0000  
2   0.028    15.2170    4.5337    3.8370  
3   0.000     0.0000    2.4388    0.5676  
4   0.000    12.4229    0.4534    0.9096  

[5 rows x 22 columns]

In [5]:
zee.columns

Index(['Run', 'Event', 'pt1', 'eta1', 'phi1', 'Q1', 'type1', 'sigmaEtaEta1',
       'HoverE1', 'isoTrack1', 'isoEcal1', 'isoHcal1', 'pt2', 'eta2', 'phi2',
       'Q2', 'type2', 'sigmaEtaEta2', 'HoverE2', 'isoTrack2', 'isoEcal2',
       'isoHcal2'],
      dtype='object')

In [6]:
zee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
Run             10000 non-null int64
Event           10000 non-null int64
pt1             10000 non-null float64
eta1            10000 non-null float64
phi1            10000 non-null float64
Q1              10000 non-null int64
type1           10000 non-null object
sigmaEtaEta1    10000 non-null float64
HoverE1         10000 non-null float64
isoTrack1       10000 non-null float64
isoEcal1        10000 non-null float64
isoHcal1        10000 non-null float64
pt2             10000 non-null float64
eta2            10000 non-null float64
phi2            10000 non-null float64
Q2              10000 non-null int64
type2           10000 non-null object
sigmaEtaEta2    10000 non-null float64
HoverE2         10000 non-null float64
isoTrack2       10000 non-null float64
isoEcal2        10000 non-null float64
isoHcal2        10000 non-null float64
dtypes: float64(16), int64(4), object(2)
mem

In [19]:
### dropping Run and Event
zee.drop(columns=['Run', 'Event'], inplace = True);

In [20]:
zee.head(5)

pt1    eta1    phi1  Q1 type1  sigmaEtaEta1  HoverE1  isoTrack1  \
0  37.5667  2.2892  2.0526  -1    EE        0.0251   0.0090     0.0000   
1  36.2901 -0.8373 -1.5859   1    EB        0.0078   0.0438     0.0000   
2  25.9705 -0.6974  1.6360  -1    EB        0.0097   0.0407     6.2870   
3  41.0075  1.4619 -0.5325   1    EB        0.0088   0.0000     0.0000   
4  39.8985 -0.5927 -2.3947   1    EB        0.0153   0.0000     2.5435   

   isoEcal1  isoHcal1      pt2    eta2    phi2  Q2 type2  sigmaEtaEta2  \
0    0.5329    0.6423  45.4315  1.4706 -1.1630   1    EB        0.0008   
1    1.4970    0.6402  60.5754 -0.4896  1.0496  -1    EB        0.0112   
2    5.0077    3.9249  45.2954 -2.0401  3.1187   1    EE        0.0260   
3    1.9670    0.5429  45.9013  1.1561  2.4786  -1    EB        0.0086   
4    4.8691    0.0000  34.8931 -2.2444  0.6106  -1    EE        0.0290   

   HoverE2  isoTrack2  isoEcal2  isoHcal2  
0    0.000     0.0000    1.0190    0.0000  
1    0.000     0.7185    1.8461    0.0000  
2    0.028    15.2170    4.5337    3.8370  
3    0.000     0.0000    2.4388    0.5676  
4    0.000    12.4229    0.4534    0.9096

### Correlations between the particles

In [25]:
groupby_charge = zee.groupby(['Q1', 'Q2'])

In [26]:
groupby_charge.describe()

pt1                                                                 \
        count       mean        std      min        25%       50%        75%   
Q1 Q2                                                                          
-1 -1  1174.0  38.034097  11.756094  25.0248  29.151950  35.07195  43.604975   
    1  3728.0  40.408350  11.067131  25.0170  32.553675  39.46325  45.427150   
 1 -1  3863.0  40.372171  11.733574  25.0054  32.691800  39.02430  45.132550   
    1  1235.0  38.014566  12.230886  25.0030  29.322050  34.88620  42.838150   

                  eta1            ...  isoEcal2          isoHcal2            \
           max   count      mean  ...       75%      max    count      mean   
Q1 Q2                             ...                                         
-1 -1  149.250  1174.0 -0.021017  ...  9.112825  35.9749   1174.0  3.645292   
    1  186.014  3728.0 -0.018164  ...  3.967350  66.6093   3728.0  1.666903   
 1 -1  252.099  3863.0  0.005269  ...  3.783200  74.7395   3863.0  1.665963   
    1  145.452  1235.0  0.024029  ...  8.983900  47.7144   1235.0  3.723662   

                                                            
            std  min       25%      50%       75%      max  
Q1 Q2                                                       
-1 -1  3.795617  0.0  0.921725  2.58360  5.115225  31.5944  
    1  2.824500  0.0  0.000000  0.68105  1.999750  37.3288  
 1 -1  2.739169  0.0  0.000000  0.67430  2.017450  40.5488  
    1  4.190901  0.0  0.995950  2.71800  5.322750  72.4930  

[4 rows x 128 columns]

In [27]:
groupby_type = zee.groupby(['type1', 'type2'])
groupby_type.describe()

pt1                                                      \
              count       mean        std      min        25%       50%   
type1 type2                                                               
EB    EB     4981.0  40.940222  11.793527  25.0030  32.790000  39.70470   
      EE     2608.0  36.696889  10.207767  25.0235  29.803450  34.87025   
EE    EB     1139.0  39.182802  11.216267  25.0301  31.074300  37.46690   
      EE     1272.0  42.407312  12.450284  25.0384  34.643925  41.84015   

                                  eta1            ...  isoEcal2           \
                  75%      max   count      mean  ...       75%      max   
type1 type2                                       ...                      
EB    EB     46.03560  186.014  4981.0 -0.007934  ...  7.156700  74.7395   
      EE     40.84890  179.268  2608.0  0.024283  ...  3.102125  48.9473   
EE    EB     44.03375  120.173  1139.0  0.053340  ...  7.990600  70.6613   
      EE     47.51630  252.099  1272.0 -0.099782  ...  3.044275  25.6824   

            isoHcal2                                                       \
               count      mean       std  min      25%      50%       75%   
type1 type2                                                                 
EB    EB      4981.0  2.051182  3.525667  0.0  0.00000  0.70190  2.618400   
      EE      2608.0  2.241993  2.885401  0.0  0.39800  1.23355  3.077925   
EE    EB      1139.0  2.261755  3.314473  0.0  0.00000  0.79140  3.209800   
      EE      1272.0  2.270386  2.590340  0.0  0.47045  1.38830  3.127875   

                      
                 max  
type1 type2           
EB    EB     72.4930  
      EE     37.3288  
EE    EB     23.0844  
      EE     21.4493  

[4 rows x 144 columns]

In [31]:
groupby_charge.ngroup()

0       1
1       2
2       1
3       2
4       2
       ..
9995    2
9996    2
9997    1
9998    2
9999    0
Length: 10000, dtype: int64

In [32]:
np.unique(groupby_charge.ngroup())

array([0, 1, 2, 3])

In [42]:
groupby_charge_type = zee.groupby(by = ['Q1','Q2','type1','type2'])
groupby_charge_type.describe()

pt1                                                      \
                    count       mean        std      min        25%       50%   
Q1 Q2 type1 type2                                                               
-1 -1 EB    EB      523.0  38.242272  12.423759  25.0460  29.172750  35.23130   
            EE      327.0  35.766123  10.197252  25.0248  28.310750  33.12020   
      EE    EB      154.0  39.812104  12.212276  25.0334  29.503000  36.82315   
            EE      170.0  40.145501  11.377922  25.1101  31.733275  39.02825   
    1 EB    EB     1946.0  41.745075  11.811937  25.0170  33.897500  40.86875   
            EE      918.0  36.814375   9.642887  25.0754  30.087650  35.25675   
      EE    EB      402.0  39.139697   9.521900  25.0850  32.261475  38.31130   
            EE      462.0  43.023073   9.808700  25.0384  36.805975  43.06795   
 1 -1 EB    EB     1947.0  41.594887  11.170010  25.0054  34.591400  40.56800   
            EE     1028.0  37.148969  10.336164  25.0235  30.427575  35.70460   
      EE    EB      417.0  39.303290  11.920153  25.0301  31.368600  37.62860   
            EE      471.0  43.299019  14.729808  25.0716  36.091350  42.09110   
    1 EB    EB      565.0  38.409512  12.518986  25.0030  29.351300  35.03140   
            EE      335.0  35.896207  11.218775  25.0515  28.357600  33.57390   
      EE    EB      166.0  38.400708  12.237850  25.1303  29.890100  35.10100   
            EE      169.0  40.514013  12.626991  25.1531  31.880900  38.70180   

                                          eta1            ...   isoEcal2  \
                         75%       max   count      mean  ...        75%   
Q1 Q2 type1 type2                                         ...              
-1 -1 EB    EB     42.958150  149.2500   523.0 -0.013016  ...  11.431150   
            EE     39.514550  104.4230   327.0  0.011729  ...   5.173900   
      EE    EB     46.841950   81.8070   154.0  0.001253  ...  11.149775   
            EE     46.058700   89.9344   170.0 -0.128798  ...   4.261175   
    1 EB    EB     46.449575  186.0140  1946.0 -0.005761  ...   4.871450   
            EE     41.044125  110.9760   918.0 -0.009584  ...   2.789750   
      EE    EB     43.523575   81.3910   402.0  0.023201  ...   5.818700   
            EE     47.864950  112.0870   462.0 -0.123447  ...   2.383500   
 1 -1 EB    EB     46.267050  153.3910  1947.0 -0.005740  ...   4.669050   
            EE     41.139475  179.2680  1028.0  0.032519  ...   2.504725   
      EE    EB     43.911800  120.1730   417.0  0.056804  ...   6.603400   
            EE     47.928800  252.0990   471.0 -0.054320  ...   2.366300   
    1 EB    EB     43.774600  145.4520   565.0 -0.018275  ...  11.734200   
            EE     39.907450  118.1380   335.0  0.104072  ...   4.303600   
      EE    EB     42.744250   88.6353   166.0  0.165946  ...  10.836425   
            EE     44.202500  101.0600   169.0 -0.132603  ...   4.430700   

                           isoHcal2                                     \
                       max    count      mean       std  min       25%   
Q1 Q2 type1 type2                                                        
-1 -1 EB    EB     35.9749    523.0  3.726014  4.001613  0.0  0.763500   
            EE     35.5448    327.0  3.596285  3.905822  0.0  1.073650   
      EE    EB     32.6479    154.0  3.847919  3.441243  0.0  1.100650   
            EE     19.2366    170.0  3.307662  3.195141  0.0  1.183450   
    1 EB    EB     66.6093   1946.0  1.599792  3.104805  0.0  0.000000   
            EE     18.4889    918.0  1.763607  2.464527  0.0  0.320250   
      EE    EB     28.3076    402.0  1.602250  2.917715  0.0  0.000000   
            EE     15.1088    462.0  1.813685  2.067907  0.0  0.335175   
 1 -1 EB    EB     74.7395   1947.0  1.467399  2.900727  0.0  0.000000   
            EE     48.9473   1028.0  1.880255  2.484343  0.0  0.312500   
      EE    EB     70.6613    417.0  1.789327  3.079148  0.0  0.000000   
 

    * There could be 16 clusters possible

### Scaling data on to the same scale

In [44]:
zee_edited = zee.drop(columns = ['Q1','Q2', 'type1', 'type2'])

In [45]:
zee_edited.columns

Index(['pt1', 'eta1', 'phi1', 'sigmaEtaEta1', 'HoverE1', 'isoTrack1',
       'isoEcal1', 'isoHcal1', 'pt2', 'eta2', 'phi2', 'sigmaEtaEta2',
       'HoverE2', 'isoTrack2', 'isoEcal2', 'isoHcal2'],
      dtype='object')

In [46]:
zee_edited.mean()

pt1             39.820004
eta1            -0.004236
phi1            -0.011530
sigmaEtaEta1     0.012418
HoverE1          0.023591
isoTrack1        5.809642
isoEcal1         4.678145
isoHcal1         2.236042
pt2             41.376158
eta2             0.008657
phi2             0.028482
sigmaEtaEta2     0.014082
HoverE2          0.020239
isoTrack2        5.291606
isoEcal2         4.303183
isoHcal2         2.152813
dtype: float64

In [47]:
zee_edited.std()

pt1             11.598636
eta1             1.207731
phi1             1.818831
sigmaEtaEta1     0.005824
HoverE1          0.041234
isoTrack1        9.850592
isoEcal1         4.885182
isoHcal1         3.344397
pt2             12.085252
eta2             1.437133
phi2             1.813896
sigmaEtaEta2     0.007175
HoverE2          0.037990
isoTrack2        9.414047
isoEcal2         4.732648
isoHcal2         3.236533
dtype: float64

In [56]:
# Checking the sparsity of the data
zee_edited[zee_edited == 0].count()

pt1                0
eta1               0
phi1               0
sigmaEtaEta1       0
HoverE1         5783
isoTrack1       4692
isoEcal1          16
isoHcal1        3338
pt2                0
eta2               0
phi2               0
sigmaEtaEta2       0
HoverE2         5686
isoTrack2       5015
isoEcal2          37
isoHcal2        2967
dtype: int64

    * Some of the columns have significant sparsity in the data

#### Train, Test split

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
randomseed = 100

In [61]:
traindata, testdata = train_test_split(zee_edited, test_size = 0.1)

In [62]:
len(traindata)

9000

In [63]:
validdata = traindata[:1000]

In [65]:
traindata = traindata[1000:]

#### Scaling

In [57]:
from sklearn.preprocessing import MinMaxScaler

In [58]:
minmaxscaler = MinMaxScaler()

In [66]:
minmaxscaled_data = minmaxscaler.fit(traindata)

In [71]:
scaled_traindata = minmaxscaled_data.transform(traindata)
scaled_validdata = minmaxscaled_data.transform(validdata)
scaled_testdata = minmaxscaled_data.transform(testdata)

In [92]:
scaled_validdata.shape

(1000, 16)

#### KMeans Clustering

In [43]:
from sklearn.cluster import KMeans

In [72]:
kmeans = KMeans(n_clusters=16)

In [73]:
kmeans.fit(scaled_traindata)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=16, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [80]:
validdata.iloc[[0]]

pt1    eta1    phi1  sigmaEtaEta1  HoverE1  isoTrack1  isoEcal1  \
6529  28.7879 -0.9938 -2.9937        0.0086      0.0        0.0    1.6318   

      isoHcal1      pt2    eta2   phi2  sigmaEtaEta2  HoverE2  isoTrack2  \
6529    3.6872  27.9529  1.0339  0.381        0.0087      0.0        0.0   

      isoEcal2  isoHcal2  
6529    2.3379    0.6547

In [97]:
scaled_traindata[0].shape

(16,)

In [98]:
kmeans.predict(scaled_validdata[0].reshape((1,-1)))

array([12], dtype=int32)

In [88]:
np.unique(kmeans.labels_, return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       dtype=int32),
 array([444, 439, 392, 482, 477, 603, 548, 558, 320, 507, 570, 613, 634,
        453, 402, 558]))

In [119]:
np.unique(kmeans.labels_, return_counts=True)[1].sum()

8000

In [103]:
traindata.index.values

array([6427, 6544, 1929, ..., 8553, 1025, 1065])

In [118]:
zee.iloc[traindata.index.values].groupby(by = ['Q1','Q2','type1','type2']).size()

Q1  Q2  type1  type2
-1  -1  EB     EB        420
               EE        265
        EE     EB        110
               EE        141
     1  EB     EB       1558
               EE        737
        EE     EB        327
               EE        361
 1  -1  EB     EB       1558
               EE        811
        EE     EB        334
               EE        386
     1  EB     EB        448
               EE        264
        EE     EB        134
               EE        146
dtype: int64

In [120]:
from sklearn.model_selection import KFold

In [121]:
cv = KFold(n_splits=10, random_state=randomseed)